# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicurl',
            name='shortcode',
            field=models.CharField(default='www.google.com', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
