# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_magicurl_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magicurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
