# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170312_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='magicurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
